FS-2506/FS-4661/FS-4618 : Adding unit tests and some of the fixes that found while fixing e2e tests (#38)
* adding new e2e

* adding new data types & data conversion logic into adapter

* adding new data types & data conversion logic into adapter

* adding new data types & data conversion logic into adapter

* adding new data types & data conversion logic into adapter

* adding new data types & data conversion logic into adapter

* adding new data types & data conversion logic into adapter

* adding artifact

* adding new data types & data conversion logic into adaptersdfsdfsd

* fix e2e

* fixes

* adding fixes

* log

* adding fixes for the build in github

* adding new data types & data conversion logic into adaptersdfsdfsd

* temp commit

* temp commit

* temp commit

* temp commit

* temp commit

* temp commit

* temp commit

* temp commit

* temp commit

* temp commit

* temp commit

* temp commit

* temp commit

* temp commit

* adding logging

* add callback handler

* add callback handler

* add callback handler

* add callback handler

* adding fixes

* adding fixes

* adding fixes

* adding fixes

* adding fixes

* adding fixes

* adding fixes

* adding fixes

* adding fixes

* adding fixes

* adding fixes

* adding fixes

* adding fixes

* adding back the changes

diff --git a/.github/workflows/copilot_deploy.yml b/.github/workflows/copilot_deploy.yml
--- a/.github/workflows/copilot_deploy.yml
+++ b/.github/workflows/copilot_deploy.yml
@@ -163,10 +163,10 @@ jobs:
           file: ./designer/Dockerfile
           build-args: |
             LAST_TAG='${{env.VERSION}}'
-            LAST_COMMIT='${{ github.sha }}'    
+            LAST_COMMIT='${{ github.sha }}'
 
   e2e-test:
-    needs: [ setup, docker-designer-build, docker-runner-build ]
+    needs: [ setup, docker-runner-build, docker-designer-build ]
     runs-on: ubuntu-latest
     name: run e2e
     outputs:
@@ -194,7 +194,7 @@ jobs:
           key: ${{ runner.os }}-yarn-e2e-${{ hashFiles('**/yarn.lock') }}
           restore-keys: |
             ${{ runner.os }}-yarn-e2e
-            ${{ runner.os }}-yarn           
+            ${{ runner.os }}-yarn  
 
       - name: Setup e2e dependencies
         run: |
@@ -211,17 +211,47 @@ jobs:
           cd digital-form-builder
           yarn
 
-      - name: start containers
-        run: |
-          docker compose -f docker-compose.e2e.yml up -d 
-          docker ps
+      - name: Start containers
+        run: docker compose -f docker-compose.e2e.yml up -d
 
-      - name: log
-        run: |
-          docker compose logs
+      - name: Create S3 bucket
+        run: docker exec localstack /bin/sh -c "awslocal s3api create-bucket --bucket fsd-bucket --create-bucket-configuration LocationConstraint=eu-west-2 --region eu-west-2"
 
-      - name: run e2e tests
+      - name: Create S3 cors
+        run: |
+          docker exec localstack /bin/sh -c "awslocal s3api put-bucket-cors --bucket fsd-bucket --cors-configuration '{\"CORSRules\": [{\"AllowedOrigins\": [\"*\"],\"AllowedMethods\": [\"GET\", \"PUT\", \"POST\", \"DELETE\", \"HEAD\"],\"AllowedHeaders\": [\"*\"]}]}'"
+
+      - name: Run e2e tests
+        id: e2e
         run: yarn e2e-test cypress run
+        continue-on-error: true
+
+      - name: Create Folders
+        run: mkdir -p ./e2e-test/cypress/screenshots/logs
+
+      - name: Get Logs from localstack
+        run: docker logs localstack > ./e2e-test/cypress/screenshots/logs/localstack.log
+
+      - name: Get Logs from runner
+        run: docker logs runner > ./e2e-test/cypress/screenshots/logs/runner.log
+
+      - name: Get all the uploaded files in the bucket
+        run: docker exec localstack /bin/sh -c "awslocal s3api list-objects --bucket fsd-bucket"
+
+      - name: Upload E2E Test Report Application
+        if: success() || failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: e2e-test-report-application
+          path: ./e2e-test/cypress/screenshots
+          retention-days: 5
+
+      - name: Check for errors & exit the job
+        run: |
+          if [ "${{ steps.e2e.outcome }}" == "failure" ]; then
+            echo "Test failures please fix before deploying the service"
+            exit 1
+          fi
 
   dev_deploy:
     strategy:
@@ -408,3 +438,4 @@ jobs:
       - name: Copilot deploy ${{ matrix.deployment }}
         run: |
           copilot ${{ matrix.command }} deploy --name ${{ matrix.deployment }}
+
