test fix

diff --git a/.github/workflows/copilot_deploy.yml b/.github/workflows/copilot_deploy.yml
--- a/.github/workflows/copilot_deploy.yml
+++ b/.github/workflows/copilot_deploy.yml
@@ -307,6 +307,28 @@ jobs:
             exit 1
           fi
 
+
+  aggregate-results:
+    needs: [e2e-test]
+    runs-on: ubuntu-latest
+    if: always()  # Ensures this job runs regardless of the matrix jobs' outcomes
+    steps:
+      - name: Check matrix job results
+        run: |
+          failed_jobs=0
+          for job in ${{ toJSON(needs) }}; do
+            if [ "${{ needs[$job].result }}" == "failure" ]; then
+              echo "Job $job failed."
+              failed_jobs=$((failed_jobs + 1))
+            fi
+          done
+          if [ "$failed_jobs" -gt 0 ]; then
+            echo "$failed_jobs job(s) failed."
+            exit 1
+          else
+            echo "All matrix jobs passed."
+          fi
+
   dev_deploy:
     needs: [ setup, docker-designer-build, docker-runner-build ]
     if: ${{ always() && contains(fromJSON(needs.setup.outputs.jobs_to_run), 'dev') && (! contains(needs.*.result, 'failure') ) && (! contains(needs.*.result, 'cancelled') ) }}
